apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name:  udagram-frontend
        image: olatunjiyso/udagram-frontend
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 50m
        type: Resource
resource:
  name: cpu
  target:
    type: Utilization
    averageUtilization: 60
        ports:
        - containerPort: 80