apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 0
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name:  udagram-api-user
        image: olatunjiyso/udagram-api-user
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: udagram-env-variable